Repository salpinoff/salpinoff_FE, pull requests merged in 2024-05, with the labels that each got.

#4 로그인 API 연동
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/app/(route)/api/auth/[...auth]/handler.ts
  src/app/(route)/api/auth/[...auth]/route.ts
  src/app/(route)/api/auth/[...auth]/utils.ts
  src/app/(route)/signin/components/kakao-login-btn.tsx
  src/app/(route)/signin/layout.tsx
  src/app/(route)/signin/page.tsx
  src/app/api/api.config.ts
  src/app/api/auth/kakao.ts
  src/app/api/auth/signin.ts
  src/app/api/auth/token.ts
  src/app/constant/api.router.ts
  src/app/constant/auth/providers.ts
  src/app/types/auth.ts
  src/app/types/env.d.ts
  src/app/utils/qs.ts
  tsconfig.json
Labels: enhancement

#11 로그인 UI - 회원 닉네임 UI
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  public/icons/info.svg
  public/icons/spin.svg
  src/app/(route)/(auth)/layout.tsx
  src/app/(route)/(auth)/signin/components/kakao-login-btn.tsx
  src/app/(route)/(auth)/signin/page.tsx
  src/app/(route)/(auth)/signup/components/MakeNickName.tsx
  src/app/(route)/(auth)/signup/page.tsx
  src/app/(route)/signin/layout.tsx
  src/app/components/FixedBottom.tsx
  src/app/components/Spinner.tsx
  src/app/components/buttons/BaseButton.tsx
  src/app/components/buttons/ModalButton.tsx
  src/app/components/inputs/TextInput.tsx
  src/app/globals.css
  src/app/hooks/useFixedBottom.tsx
  src/app/layout.tsx
  src/app/types/svg.d.ts
  src/app/types/utility.ts
  src/app/utils/cn.ts
  tsconfig.json
Labels: feature

#18 [FEAT] 공통 컴포넌트 구현
  .commitlintrc.json
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  public/icons/error.svg
  src/app/components/common/Badge/Badge.stories.tsx
  src/app/components/common/Badge/index.tsx
  src/app/components/common/FormLabel/FormLabel.stories.tsx
  src/app/components/common/FormLabel/index.tsx
  src/app/components/common/Icon/index.tsx
  src/app/components/common/Text/BaseText.tsx
  src/app/components/common/Text/Text.constants.ts
  src/app/components/common/Text/Text.stories.tsx
  src/app/components/common/TextField/FormHelperText.tsx
  src/app/components/common/TextField/index.tsx
  src/app/components/common/Tooltip/index.tsx
  src/app/types/util.ts
  tailwind.config.ts
Labels: component

#26 Button 컴포넌트 추가 구현
  .storybook/main.ts
  src/app/components/common/Button/Button.stories.tsx
  src/app/components/common/Button/index.tsx
Labels: component
